### ISSUE TITLE
Unable to Commit Tasks on Chain

### ISSUE THREAD

**Issue by andrewtam** [enigmampc/surface#6]
I'm currently testing my voting contract with the testnet. However, I am getting some errors at the end of the process (where results are committed on chain). Here is the full error log:
```

[2018-07-17 21:35:34.241043] INFO: main: Listening for new tasks
[2018-07-17 21:35:45.287073] DEBUG: main: TaskId: 716b7ca72477d183b0490ff7426347de6ba51192a1ce29554ecf673f613b5e2d
[2018-07-17 21:35:45.424854] INFO: main: the bytecode: 0x6080604052600436106100b95763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416634e0e931a81146100be5780635be5e3ec146100f05780635fc48d7e1461011057806365847632146101345780639207891d14610158578063ac2f00741461017f578063b0c095e314610250578063b24fd5c51461028c578063ba7bd2aa146102bd578063d2025b1d146102d8578063f43b877814610389578063fc0c546a146103a1575b600080fd5b3480156100ca57600080fd5b506100dc6004356024356044356103b6565b604080519115158252519081900360200190f35b3480156100fc57600080fd5b5061010e6004356024356044356103f8565b005b34801561011c57600080fd5b506100dc600435600160a060020a03602435166105d3565b34801561014057600080fd5b5061010e60048035906024803590810191013561065b565b34801561016457600080fd5b5061016d6107c0565b60408051918252519081900360200190f35b34801561018b57600080fd5b506101976004356107c6565b604051600160a060020a0388168152602081018760038111156101b657fe5b60ff16815260200186815260200185815260200184815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b8381101561020f5781810151838201526020016101f7565b50505050905090810190601f16801561023c5780820380516001836020036101000a031916815260200191505b509850505050505050505060405180910390f35b34801561025c57600080fd5b506102686004356108ae565b6040518082600381111561027857fe5b60ff16815260200191505060405180910390f35b34801561029857600080fd5b506102a1610936565b60408051600160a060020a039092168252519081900360200190f35b3480156102c957600080fd5b5061010e600435602435610945565b3480156102e457600080fd5b5060408051602060046024803582810135848102808701860190975280865261036b96843596369660449591949091019291829185019084908082843750506040805187358901803560208181028481018201909552818452989b9a998901989297509082019550935083925085019084908082843750949750610bcb9650505050505050565b60408051938452602084019290925282820152519081900360600190f35b34801561039557600080fd5b5061010e600435610c5d565b3480156103ad57600080fd5b506102a1610e16565b604080516001815290516000917f6d159032c96b1814e4098508b3ee8411d61418775de83eca0ae80972a779b63e919081900360200190a15060019392505050565b60008360008111801561040d57506001548111155b1515610451576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b600061045c866108ae565b600381111561046757fe5b146104bc576040805160e560020a62461bcd02815260206004820152601160248201527f506f6c6c2068617320657870697265642e000000000000000000000000000000604482015290519081900360640190fd5b6104c685336105d3565b1561051b576040805160e560020a62461bcd02815260206004820152601760248201527f557365722068617320616c726561647920766f7465642e000000000000000000604482015290519081900360640190fd5b6105253384610e25565b60008581526020818152604080832081516060808201845260018083528286018b81528386018b815233808a52600687018952988790209451855460ff1916901515178555905184830155516002909301929092556004830180549092019091558251948552928401899052838201889052918301869052519093507f24e8f28bcf1dbc2f2cbdaf38b4ed8c435d3ac3b055bd15be18b06645b29dba1d916080908290030190a15050505050565b6000826000811180156105e857506001548111155b151561062c576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b5050600091825260208281526040808420600160a060020a039390931684526006909201905290205460ff1690565b600060648411156106dc576040805160e560020a62461bcd02815260206004820152603460248201527f51756f72756d2050657263656e74616765206d757374206265206c657373207460448201527f68616e206f7220657175616c20746f2031303025000000000000000000000000606482015290519081900360840190fd5b506001805481018082556000908152602081905260409020805473ffffffffffffffffffffffffffffffffffffffff1916331774ff00000000000000000000000000000000000000001916815590810184905561073d600582018484611032565b507fc504d9ec32644c55801c38afe2a56cc0b06be98d7fe9debdab0fcf28fa99cf7d600154853386866040518086815260200185815260200184600160a060020a0316600160a060020a0316815260200180602001828103825284848281815260200192508082843760405192018290039850909650505050505050a150505050565b60015481565b600060208181529181526040908190208054600180830154600280850154600386015460048701546005880180548a516101009882161598909802600019011694909404601f81018b90048b0287018b01909952888652600160a060020a038716997401000000000000000000000000000000000000000090970460ff169894979296919590949293909290918301828280156108a45780601f10610879576101008083540402835291602001916108a4565b820191906000526020600020905b81548152906001019060200180831161088757829003601f168201915b5050505050905087565b6000816000811180156108c357506001548111155b1515610907576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b505060009081526020819052604090205474010000000000000000000000000000000000000000900460ff1690565b600354600160a060020a031681565b8060008111801561095857506001548111155b151561099c576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b60036109a7836108ae565b60038111156109b257fe5b14806109d1575060026109c4836108ae565b60038111156109cf57fe5b145b1515610a27576040805160e560020a62461bcd02815260206004820152601560248201527f506f6c6c20686173206e6f7420657870697265642e0000000000000000000000604482015290519081900360640190fd5b610a3182336105d3565b1515610a87576040805160e560020a62461bcd02815260206004820152601e60248201527f5573657220646964206e6f7420766f746520696e2074686520706f6c6c2e0000604482015290519081900360640190fd5b600082815260208181526040808320338452600601909152902060020154831115610b22576040805160e560020a62461bcd02815260206004820152602b60248201527f5573657220697320747279696e6720746f20776974686472617720746f6f206d60448201527f616e7920746f6b656e732e000000000000000000000000000000000000000000606482015290519081900360840190fd5b600254604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152336004820152602481018690529051600160a060020a039092169163a9059cbb916044808201926020929091908290030181600087803b158015610b8f57600080fd5b505af1158015610ba3573d6000803e3d6000fd5b505050506040513d6020811015610bb957600080fd5b50511515610bc657600080fd5b505050565b60008060008084518651141515610bde57fe5b5060005b8551811015610c51578581815181101515610bf957fe5b9060200190602002015160001415610c2c578481815181101515610c1957fe5b9060200190602002015182019150610c49565b8481815181101515610c3a57fe5b90602001906020020151830192505b600101610be2565b50949590949350915050565b80600081118015610c7057506001548111155b1515610cb4576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b600082815260208190526040902054600160a060020a03163314610d47576040805160e560020a62461bcd028152602060048201526024808201527f55736572206973206e6f74207468652063726561746f72206f6620746865207060448201527f6f6c6c2e00000000000000000000000000000000000000000000000000000000606482015290519081900360840190fd5b6000808381526020819052604090205474010000000000000000000000000000000000000000900460ff166003811115610d7d57fe5b14610dd2576040805160e560020a62461bcd02815260206004820152601860248201527f566f7465206973206e6f7420696e2070726f67726573732e0000000000000000604482015290519081900360640190fd5b506000908152602081905260409020805474ff0000000000000000000000000000000000000000191674010000000000000000000000000000000000000000179055565b600254600160a060020a031681565b600254604080517f70a08231000000000000000000000000000000000000000000000000000000008152600160a060020a0385811660048301529151849392909216916370a08231916024808201926020929091908290030181600087803b158015610e9057600080fd5b505af1158015610ea4573d6000803e3d6000fd5b505050506040513d6020811015610eba57600080fd5b50511015610f12576040805160e560020a62461bcd02815260206004820181905260248201527f5573657220646f6573206e6f74206861766520656e6f75676820746f6b656e73604482015290519081900360640190fd5b600254604080517f23b872dd000000000000000000000000000000000000000000000000000000008152600160a060020a03858116600483015230602483015260448201859052915191909216916323b872dd9160648083019260209291908290030181600087803b158015610f8757600080fd5b505af1158015610f9b573d6000803e3d6000fd5b505050506040513d6020811015610fb157600080fd5b5051151561102e576040805160e560020a62461bcd028152602060048201526024808201527f5573657220646964206e6f7420617070726f766520746f6b656e207472616e7360448201527f6665722e00000000000000000000000000000000000000000000000000000000606482015290519081900360840190fd5b5050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106110735782800160ff198235161785556110a0565b828001600101855582156110a0579182015b828111156110a0578235825591602001919060010190611085565b506110ac9291506110b0565b5090565b6110ca91905b808211156110ac57600081556001016110b6565b9056004e6f7420612076616c696420706f6c6c2049642e000000000000000000000000a165627a7a72305820ce082e43b0715141bc72cb196b0eee2e438959198fd5a9f6bc73e06ea632d51f0029
[2018-07-17 21:35:45.425597] INFO: Node: sending task to Core for private computation
[2018-07-17 21:35:45.425822] DEBUG: Node: Sending To EVM:{'cmd': 'execevm', 'bytecode': '6080604052600436106100b95763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416634e0e931a81146100be5780635be5e3ec146100f05780635fc48d7e1461011057806365847632146101345780639207891d14610158578063ac2f00741461017f578063b0c095e314610250578063b24fd5c51461028c578063ba7bd2aa146102bd578063d2025b1d146102d8578063f43b877814610389578063fc0c546a146103a1575b600080fd5b3480156100ca57600080fd5b506100dc6004356024356044356103b6565b604080519115158252519081900360200190f35b3480156100fc57600080fd5b5061010e6004356024356044356103f8565b005b34801561011c57600080fd5b506100dc600435600160a060020a03602435166105d3565b34801561014057600080fd5b5061010e60048035906024803590810191013561065b565b34801561016457600080fd5b5061016d6107c0565b60408051918252519081900360200190f35b34801561018b57600080fd5b506101976004356107c6565b604051600160a060020a0388168152602081018760038111156101b657fe5b60ff16815260200186815260200185815260200184815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b8381101561020f5781810151838201526020016101f7565b50505050905090810190601f16801561023c5780820380516001836020036101000a031916815260200191505b509850505050505050505060405180910390f35b34801561025c57600080fd5b506102686004356108ae565b6040518082600381111561027857fe5b60ff16815260200191505060405180910390f35b34801561029857600080fd5b506102a1610936565b60408051600160a060020a039092168252519081900360200190f35b3480156102c957600080fd5b5061010e600435602435610945565b3480156102e457600080fd5b5060408051602060046024803582810135848102808701860190975280865261036b96843596369660449591949091019291829185019084908082843750506040805187358901803560208181028481018201909552818452989b9a998901989297509082019550935083925085019084908082843750949750610bcb9650505050505050565b60408051938452602084019290925282820152519081900360600190f35b34801561039557600080fd5b5061010e600435610c5d565b3480156103ad57600080fd5b506102a1610e16565b604080516001815290516000917f6d159032c96b1814e4098508b3ee8411d61418775de83eca0ae80972a779b63e919081900360200190a15060019392505050565b60008360008111801561040d57506001548111155b1515610451576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b600061045c866108ae565b600381111561046757fe5b146104bc576040805160e560020a62461bcd02815260206004820152601160248201527f506f6c6c2068617320657870697265642e000000000000000000000000000000604482015290519081900360640190fd5b6104c685336105d3565b1561051b576040805160e560020a62461bcd02815260206004820152601760248201527f557365722068617320616c726561647920766f7465642e000000000000000000604482015290519081900360640190fd5b6105253384610e25565b60008581526020818152604080832081516060808201845260018083528286018b81528386018b815233808a52600687018952988790209451855460ff1916901515178555905184830155516002909301929092556004830180549092019091558251948552928401899052838201889052918301869052519093507f24e8f28bcf1dbc2f2cbdaf38b4ed8c435d3ac3b055bd15be18b06645b29dba1d916080908290030190a15050505050565b6000826000811180156105e857506001548111155b151561062c576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b5050600091825260208281526040808420600160a060020a039390931684526006909201905290205460ff1690565b600060648411156106dc576040805160e560020a62461bcd02815260206004820152603460248201527f51756f72756d2050657263656e74616765206d757374206265206c657373207460448201527f68616e206f7220657175616c20746f2031303025000000000000000000000000606482015290519081900360840190fd5b506001805481018082556000908152602081905260409020805473ffffffffffffffffffffffffffffffffffffffff1916331774ff00000000000000000000000000000000000000001916815590810184905561073d600582018484611032565b507fc504d9ec32644c55801c38afe2a56cc0b06be98d7fe9debdab0fcf28fa99cf7d600154853386866040518086815260200185815260200184600160a060020a0316600160a060020a0316815260200180602001828103825284848281815260200192508082843760405192018290039850909650505050505050a150505050565b60015481565b600060208181529181526040908190208054600180830154600280850154600386015460048701546005880180548a516101009882161598909802600019011694909404601f81018b90048b0287018b01909952888652600160a060020a038716997401000000000000000000000000000000000000000090970460ff169894979296919590949293909290918301828280156108a45780601f10610879576101008083540402835291602001916108a4565b820191906000526020600020905b81548152906001019060200180831161088757829003601f168201915b5050505050905087565b6000816000811180156108c357506001548111155b1515610907576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b505060009081526020819052604090205474010000000000000000000000000000000000000000900460ff1690565b600354600160a060020a031681565b8060008111801561095857506001548111155b151561099c576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b60036109a7836108ae565b60038111156109b257fe5b14806109d1575060026109c4836108ae565b60038111156109cf57fe5b145b1515610a27576040805160e560020a62461bcd02815260206004820152601560248201527f506f6c6c20686173206e6f7420657870697265642e0000000000000000000000604482015290519081900360640190fd5b610a3182336105d3565b1515610a87576040805160e560020a62461bcd02815260206004820152601e60248201527f5573657220646964206e6f7420766f746520696e2074686520706f6c6c2e0000604482015290519081900360640190fd5b600082815260208181526040808320338452600601909152902060020154831115610b22576040805160e560020a62461bcd02815260206004820152602b60248201527f5573657220697320747279696e6720746f20776974686472617720746f6f206d60448201527f616e7920746f6b656e732e000000000000000000000000000000000000000000606482015290519081900360840190fd5b600254604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152336004820152602481018690529051600160a060020a039092169163a9059cbb916044808201926020929091908290030181600087803b158015610b8f57600080fd5b505af1158015610ba3573d6000803e3d6000fd5b505050506040513d6020811015610bb957600080fd5b50511515610bc657600080fd5b505050565b60008060008084518651141515610bde57fe5b5060005b8551811015610c51578581815181101515610bf957fe5b9060200190602002015160001415610c2c578481815181101515610c1957fe5b9060200190602002015182019150610c49565b8481815181101515610c3a57fe5b90602001906020020151830192505b600101610be2565b50949590949350915050565b80600081118015610c7057506001548111155b1515610cb4576040805160e560020a62461bcd02815260206004820152601460248201526000805160206110ce833981519152604482015290519081900360640190fd5b600082815260208190526040902054600160a060020a03163314610d47576040805160e560020a62461bcd028152602060048201526024808201527f55736572206973206e6f74207468652063726561746f72206f6620746865207060448201527f6f6c6c2e00000000000000000000000000000000000000000000000000000000606482015290519081900360840190fd5b6000808381526020819052604090205474010000000000000000000000000000000000000000900460ff166003811115610d7d57fe5b14610dd2576040805160e560020a62461bcd02815260206004820152601860248201527f566f7465206973206e6f7420696e2070726f67726573732e0000000000000000604482015290519081900360640190fd5b506000908152602081905260409020805474ff0000000000000000000000000000000000000000191674010000000000000000000000000000000000000000179055565b600254600160a060020a031681565b600254604080517f70a08231000000000000000000000000000000000000000000000000000000008152600160a060020a0385811660048301529151849392909216916370a08231916024808201926020929091908290030181600087803b158015610e9057600080fd5b505af1158015610ea4573d6000803e3d6000fd5b505050506040513d6020811015610eba57600080fd5b50511015610f12576040805160e560020a62461bcd02815260206004820181905260248201527f5573657220646f6573206e6f74206861766520656e6f75676820746f6b656e73604482015290519081900360640190fd5b600254604080517f23b872dd000000000000000000000000000000000000000000000000000000008152600160a060020a03858116600483015230602483015260448201859052915191909216916323b872dd9160648083019260209291908290030181600087803b158015610f8757600080fd5b505af1158015610f9b573d6000803e3d6000fd5b505050506040513d6020811015610fb157600080fd5b5051151561102e576040805160e560020a62461bcd028152602060048201526024808201527f5573657220646964206e6f7420617070726f766520746f6b656e207472616e7360448201527f6665722e00000000000000000000000000000000000000000000000000000000606482015290519081900360840190fd5b5050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106110735782800160ff198235161785556110a0565b828001600101855582156110a0579182015b828111156110a0578235825591602001919060010190611085565b506110ac9291506110b0565b5090565b6110ca91905b808211156110ac57600081556001016110b6565b9056004e6f7420612076616c696420706f6c6c2049642e000000000000000000000000a165627a7a72305820ce082e43b0715141bc72cb196b0eee2e438959198fd5a9f6bc73e06ea632d51f0029', 'callable': 'countVotes(uint256, uint256[], uint256[])', 'callable_args': 'c501c101c10a', 'preprocessors': [], 'callback': 'updatePollStatus(uint256, uint256, uint256)'}
[2018-07-17 21:35:45.486782] INFO: Node: Outputs: 
[2018-07-17 21:35:45.487083] INFO: Node: Signature of outputs: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

[2018-07-17 21:35:45.487339] INFO: Worker: committing results for task: {'block_number': 223, 'task_id': '716b7ca72477d183b0490ff7426347de6ba51192a1ce29554ecf673f613b5e2d', 'data': '', 'sig': '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'contract_address': '0xA3C3aceCBc0B970506298141B61cF34D689Fd265'}
Traceback (most recent call last):
  File "src/surface/__main__.py", line 189, in <module>
    start(obj={})
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "src/surface/__main__.py", line 138, in start
    handle_task(w3, worker, task, block, core_socket)
  File "src/surface/__main__.py", line 181, in handle_task
    task.taskId, results, sig, block)
  File "/Users/andrew/Desktop/Andrew/secret-contracts/surface/src/surface/communication/core/worker.py", line 184, in commit_results
    task_id, data, sig, block_number
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/web3/contract.py", line 1025, in __call__
    clone._set_function_info()
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/web3/contract.py", line 1034, in _set_function_info
    self.kwargs
  File "/Users/andrew/anaconda/envs/py36/lib/python3.6/site-packages/web3/utils/contracts.py", line 128, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `commitResults`, positional argument(s) of type `(<class 'bytes'>, <class 'str'>, <class 'str'>, <class 'int'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `commitResults`: ['commitResults(bytes32,bytes,bytes,uint256)']
Function invocation failed due to no matching argument types.
```

**Comment by elichai** [comment]
It seems like the execution failed. can you post the logs from `enigma-core`?

**Comment by moriaab** [comment]
Please delete all whitespaces in callable and callback names and try. It should fix the issue.

**Comment by elichai** [comment]
This issue was moved to enigmampc/surface-internal#3
